FROM --platform=linux/amd64 node:20-alpine AS builder

WORKDIR /app

COPY ./frontend/package.json ./frontend/package-lock.json ./

RUN mkdir nginx
COPY ./nginx/nginx.conf app/nginx/
RUN npm install

COPY ./frontend ./

RUN npm run build

FROM nginx:stable-alpine

RUN mkdir /app

COPY --from=builder /app/dist /app/build
COPY --from=builder /app/nginx/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]