version: '3.8'

services:
  db:
    image: timescale/timescaledb:latest-pg15
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5433:5432"

  api:
    image: ghcr.io/mikeboe/simple-api-load-tester-api:latest
    container_name: api
    build:
      dockerfile: Dockerfile.api
    environment:
      - DB_STRING=postgres://postgres:password@db:5433/postgres
    depends_on:
      - db
    ports:
      - "8000:8000"

  rest-api:
    image: ghcr.io/mikeboe/simple-api-load-tester-rest:latest
    container_name: rest-api
    build:
      dockerfile: Dockerfile.rest-api
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:password@db:5433/postgres
      NODE_ENV: development
      PORT: 3000

  # loadTest:
  #   build: ./loadTest
  #   depends_on:
  #     - api
  #   environment:
  #     - CRON_SCHEDULE="* * * * *" # Example cron schedule, replace with your desired schedule
  #     - DB_HOST=db
  #     - DB_PORT=5432
  #     - API_HOST=api
  #     - API_PORT=8000

  frontend:
    image: ghcr.io/mikeboe/simple-api-load-tester-frontend:latest
    container_name: frontend
    build:
      dockerfile: Dockerfile.frontend
    ports:
      - "4000:80"
    depends_on:
      - api
      - rest-api

volumes:
  pgdata:
