version: '3.8'

services:
  db:
    image: timescale/timescaledb:latest-pg15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  api:
    image: ghcr.io/mikeboe/simple-api-load-tester-api:latest
    build:
      dockerfile: Dockerfile.api
    environment:
      - DB_STRING=postgres://postgres:password@db:5432/postgres
    depends_on:
      - db
    ports:
      - "8000:8000"

  # loadTest:
  #   build: ./loadTest
  #   depends_on:
  #     - api
  #   environment:
  #     - CRON_SCHEDULE="* * * * *" # Example cron schedule, replace with your desired schedule
  #     - DB_HOST=db
  #     - DB_PORT=5432
  #     - API_HOST=api
  #     - API_PORT=8000

  frontend:
    image: ghcr.io/mikeboe/simple-api-load-tester-frontend:latest
    build:
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:80"
    depends_on:
      - api

volumes:
  pgdata:
