name: Publish Frontend Docker
on:
  push:
    paths:
      - frontend/**
    branches:
      - main

env:
  REGISTRY: ghcr.io

jobs:
  publish:
    #    if: github.event.pull_request.merged == true
    name: Publish Frontend Docker
    runs-on: ubuntu-latest
    environment: Dev
    permissions: write-all
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 'Use NodeJS 20'
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install # will run `yarn install` command

      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # - name: Create Release
      #   uses: cycjimmy/semantic-release-action@v4
      #   id: release
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     working_directory: ./frontend
      #     tag_format: frontend-v${version}
      #     extends: semantic-release-monorepo

      - name: get time version
        run: |
          echo "date=$(date +'%Y-%m-%d_%H-%M')" >> $GITHUB_OUTPUT
        id: release  # this is used on variable path
      
      - name: Publish Docker to GHCR.IO
        run: |
          docker build -t frontend -f Dockerfile .
          docker tag frontend ${{ env.REGISTRY }}/mikeboe/simple-api-load-tester-frontend:latest
          docker push ${{ env.REGISTRY }}/mikeboe/simple-api-load-tester-frontend:latest
          docker tag ${{ env.REGISTRY }}/mikeboe/simple-api-load-tester-frontend:latest ${{ env.REGISTRY }}/mikeboe/simple-api-load-tester-frontend:${{ steps.release.outputs.date }}
          docker push ${{ env.REGISTRY }}/mikeboe/simple-api-load-tester-frontend:${{ steps.release.outputs.date }}
