name: Publish API Docker
on:
  push:
    paths:
      - api/**
    branches:
      - main
      
env:
  REGISTRY: ghcr.io

jobs:
  publish:
    #    if: github.event.pull_request.merged == true
    name: Publish API Docker
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 'Setup Go'
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: get time version
        run: |
          echo "date=$(date +'%Y-%m-%d_%H-%M')" >> $GITHUB_OUTPUT
        id: release # this is used on variable path

      - name: Publish Docker to GHCR.IO
        run: |
          docker build -t api -f Dockerfile.api .
          docker tag api ${{ env.REGISTRY }}/mikeboe/simple-api-load-tester-api:latest
          docker push ${{ env.REGISTRY }}/mikeboe/simple-api-load-tester-api:latest
          docker tag ${{ env.REGISTRY }}/mikeboe/simple-api-load-tester-api ${{ env.REGISTRY }}/mikeboe/simple-api-load-tester-api:${{ steps.release.outputs.date }}
          docker push ${{ env.REGISTRY }}/mikeboe/simple-api-load-tester-api:${{ steps.release.outputs.date }}